-- Agregar nuevas columnas a Configuraciones
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='ColorMenu')
BEGIN
	ALTER TABLE Configuraciones ADD ColorMenu NVARCHAR(7) NOT NULL DEFAULT '#2c3e50';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='ColorBotones')
BEGIN
	ALTER TABLE Configuraciones ADD ColorBotones NVARCHAR(7) NOT NULL DEFAULT '#667eea';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='ColorDashboard')
BEGIN
	ALTER TABLE Configuraciones ADD ColorDashboard NVARCHAR(7) NOT NULL DEFAULT '#ecf0f1';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='TemaSeleccionado')
BEGIN
	ALTER TABLE Configuraciones ADD TemaSeleccionado NVARCHAR(50) NOT NULL DEFAULT 'Fashion Store';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='RutaImagenLogin')
BEGIN
	ALTER TABLE Configuraciones ADD RutaImagenLogin NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='RutaBanner')
BEGIN
	ALTER TABLE Configuraciones ADD RutaBanner NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='RutaFondoMenu')
BEGIN
	ALTER TABLE Configuraciones ADD RutaFondoMenu NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='FacebookUrl')
BEGIN
	ALTER TABLE Configuraciones ADD FacebookUrl NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='InstagramUrl')
BEGIN
	ALTER TABLE Configuraciones ADD InstagramUrl NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='TwitterUrl')
BEGIN
	ALTER TABLE Configuraciones ADD TwitterUrl NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='LinkedInUrl')
BEGIN
	ALTER TABLE Configuraciones ADD LinkedInUrl NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='TikTokUrl')
BEGIN
	ALTER TABLE Configuraciones ADD TikTokUrl NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Configuraciones' AND COLUMN_NAME='TextoPiePagina')
BEGIN
	ALTER TABLE Configuraciones ADD TextoPiePagina NVARCHAR(MAX) NULL;
END

-- Crear tabla ConfiguracionesAuditoria
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ConfiguracionesAuditoria')
BEGIN
	CREATE TABLE ConfiguracionesAuditoria (
		Id INT PRIMARY KEY IDENTITY(1,1),
		UsuarioId NVARCHAR(450) NOT NULL,
		NombreUsuario NVARCHAR(100) NULL,
		PropiedadModificada NVARCHAR(100) NOT NULL,
		ValorAnterior NVARCHAR(MAX) NULL,
		ValorNuevo NVARCHAR(MAX) NULL,
		FechaCambio DATETIME2 NOT NULL,
		Descripcion NVARCHAR(MAX) NULL,
		CONSTRAINT FK_ConfiguracionesAuditoria_AspNetUsers FOREIGN KEY (UsuarioId) REFERENCES AspNetUsers(Id)
	);

	-- Crear índice en FechaCambio
	CREATE INDEX IX_ConfiguracionesAuditoria_FechaCambio ON ConfiguracionesAuditoria(FechaCambio DESC);
END
